[package]
name = "picorust"
version = "0.1.1"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]

build   = "build.rs"

[lib]
name = "picorust"
path = "src/lib.rs"

[dependencies]
libc = "0.2.12"

[build-dependencies]
gcc  = "^0.3.28"